### ISSUE TITLE
Customize blaze-template loginButtons

### ISSUE THREAD

**Issue by yobre** [Urigo/angular-blaze-template#13]
Hi @Urigo ,
i'm trying to customize the 

``` html
<blaze-template name="loginButtons"></blaze-template>
```

Result:
![2](https://cloud.githubusercontent.com/assets/5311396/12482972/c6877b8c-c052-11e5-9b95-1455e76bca5c.png)

in this way ([as specified here](https://atmospherejs.com/urigo/angular-blaze-template)):

``` html
<blaze-template name="loginButtons" replace> 
    <div style="color: white">
      <b>Foo</b>
    </div>
</blaze-template>
```

Result:
![1](https://cloud.githubusercontent.com/assets/5311396/12482963/bd0afcd2-c052-11e5-8e85-45ae918d3a8f.png)

I would simply change the component in terms of graphics. How can I do?
I think I misinterpreting the documentation.

Thanks

**Comment by Urigo** [comment]
@carlosbaraza

**Comment by carlosbaraza** [comment]
Hi @yobre,

The replace directive acts like the angular replace, which just removes the root element and puts the content of the template in its place. The default behavior is keeping the root element and putting the template content as child of it.

For the behavior that you want, you need to create a new template with your content.

Maybe we should specify that it works like the angular replace in the docs.

**Comment by Urigo** [comment]
@carlosbaraza can you pull request to readme to maybe clarify it more or there is no need?

**Comment by carlosbaraza** [comment]
Hi @Urigo,

I will update the docs.

Kind regards,
Carlos.
