### ISSUE TITLE
Doesn't work with IronRouter

### ISSUE THREAD

**Issue by danielflippance** [Urigo/angular-blaze-template#15]
I've added this template into my angular /client/index.html:

```
<head>
    <base href="/"> 
</head>

<template name="ironrouternotfound">
    IR Not Found
</template>

<body>
    <div ng-app="myapp" ng-strict-di="">     
        <div ui-view autoscroll="true"></div>
    </div>  
    <blaze-template name="ironrouternotfound"></blaze-template>
</body>
```

Configured IronRouter to use it - /client/router.js

```
Router.configure({
    notFoundTemplate: "ironrouternotfound"
});
```

However I still see the default IronRouter message:

"Couldn't find a template named "ironrouternotfound" or "ironrouternotfound". Are you sure you defined it?"

**Comment by Urigo** [comment]
I think the solution you are looking for can be foud here: http://stackoverflow.com/questions/31035196/iron-router-conflict-with-angular-ui-router
Please re-open if I'm not corrent
