### ISSUE TITLE
loginButtons blaze template not working with 0.1.0

### ISSUE THREAD

**Issue by dweaver** [Urigo/angular-blaze-template#2]
When we upgraded meteor and this plugin from 0.0.1 to 0.1.0 just now, Auth0 log out button doesn't appear at all and log in button doesn't do anything when you click on it. Downgrading to 0.0.1 but keeping all the other meteor upgraded packages fixed it. I'll try and make a simpler repro setup to see if it affects anything besides Auth0.

Which commit was the 0.0.1 release?

**Comment by Urigo** [comment]
@dweaver can you please test it now with version `0.1.1` ?

**Comment by Urigo** [comment]
Fixed
