### ISSUE TITLE
Should (or will) angular-blaze-template work with meteor-angular2?

### ISSUE THREAD

**Issue by drewlio** [Urigo/angular-blaze-template#6]
_Edited this comment to make it more helpful to others_

Thanks for everything you've done, Uri and Alex. I was interested in some way to do minimal server-side templates. 

Found the following:
https://github.com/Urigo/Meteor-Angular2/issues/9 and https://github.com/Urigo/Meteor-Angular2/issues/14 are closed issues to add blaze support to meteor-angular2 (won't be implemented, meteor's responsibility to handle two html processors but that doesn't exist yet)

**Comment by Urigo** [comment]
@drewlio I've added the note here - https://github.com/Urigo/Meteor-Angular2/issues/14
We will support working with Blaze and Angular 2.0 in the same application and write a migration tutorial.
If anyone wants to help, please join the discussion there.
